name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: clojure:lein
    steps: 
      - uses: actions/checkout@v3
      - name: Run Clj-kondo
        run: |
          apt-get update
          apt-get install -y zip
          curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
          chmod +x install-clj-kondo
          ./install-clj-kondo
          clj-kondo --lint src
